cargo-features = ["resolver"]

[package]
name = "cubes"
version = "0.1.0"
authors = ["george"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.24.0"
wgpu = "0.7.1"
nalgebra = "0.26.1"
